"""``TemplateManager`` and ``AssetManager`` -- reusable templates and inlined assets.

**Templates are formatted, never evaluated.** Substitution uses ``str.Template``, which understands
``$name`` and nothing else -- no expressions, no attribute traversal, no arbitrary code. A report
template is a file an operator edits, and a templating language that can execute would make styling
a report into a code-execution surface for a security tool.

That rules out Jinja here despite it being a dependency already: Jinja's power is exactly the
property this use does not want.

**Assets are inlined, not linked.** A report is emailed, attached to a ticket, and opened from a
downloads folder six months later. One that depends on a sibling CSS file is broken in all three
situations.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from string import Template
from typing import Any

#: Ships with the engine so a report renders with no configuration. Deliberately one self-contained
#: block -- see the module docstring on inlining.
DEFAULT_CSS = """
:root {
  --bg: #ffffff; --fg: #1a1a1a; --muted: #666; --border: #e2e2e2;
  --critical: #b00020; --high: #d9480f; --medium: #b8860b; --low: #1864ab; --info: #666;
  --pass: #2b8a3e; --fail: #b00020; --inconclusive: #0b7285;
}
@media (prefers-color-scheme: dark) {
  :root { --bg: #16181c; --fg: #e8e8e8; --muted: #9aa0a6; --border: #2c2f36; }
}
* { box-sizing: border-box; }
body {
  margin: 0; padding: 2rem; background: var(--bg); color: var(--fg);
  font: 15px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  max-width: 1100px; margin-inline: auto;
}
h1, h2, h3 { line-height: 1.25; }
h1 { font-size: 1.9rem; margin-bottom: .25rem; }
h2 { font-size: 1.35rem; margin-top: 2.5rem; border-bottom: 1px solid var(--border);
     padding-bottom: .4rem; }
h3 { font-size: 1.05rem; margin-top: 1.75rem; }
table { border-collapse: collapse; width: 100%; margin: 1rem 0; font-size: .93rem; }
th, td { text-align: left; padding: .5rem .7rem; border-bottom: 1px solid var(--border);
         vertical-align: top; }
th { font-weight: 600; color: var(--muted); font-size: .82rem; text-transform: uppercase;
     letter-spacing: .04em; }
code, pre { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: .87em; }
pre { background: rgba(127,127,127,.09); padding: .8rem 1rem; border-radius: 6px;
      overflow-x: auto; white-space: pre-wrap; word-break: break-word; }
.badge { display: inline-block; padding: .12rem .55rem; border-radius: 999px;
         font-size: .76rem; font-weight: 600; letter-spacing: .02em; }
.sev-CRITICAL { background: var(--critical); color: #fff; }
.sev-HIGH { background: var(--high); color: #fff; }
.sev-MEDIUM { background: var(--medium); color: #fff; }
.sev-LOW { background: var(--low); color: #fff; }
.sev-INFO { background: var(--info); color: #fff; }
.st-FAIL { color: var(--fail); font-weight: 700; }
.st-PASS { color: var(--pass); font-weight: 700; }
.st-INCONCLUSIVE { color: var(--inconclusive); font-weight: 700; }
.st-ERROR, .st-SKIPPED { color: var(--muted); font-weight: 700; }
.summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
           gap: .8rem; margin: 1.25rem 0; }
.card { border: 1px solid var(--border); border-radius: 8px; padding: .8rem 1rem; }
.card .label { color: var(--muted); font-size: .78rem; text-transform: uppercase;
               letter-spacing: .04em; }
.card .value { font-size: 1.5rem; font-weight: 650; margin-top: .15rem; }
.finding { border: 1px solid var(--border); border-radius: 8px; padding: 1rem 1.25rem;
           margin: 1rem 0; }
.headline { font-size: 1.05rem; padding: .9rem 1.1rem; border-radius: 8px;
            background: rgba(127,127,127,.09); margin: 1rem 0; }
.muted { color: var(--muted); }
footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border);
         color: var(--muted); font-size: .85rem; }
"""

#: The shipped HTML shell. ``$body`` receives rendered sections; everything else is branding.
DEFAULT_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>$title</title>
<style>$css</style>
</head>
<body>
$body
<footer>$footer</footer>
</body>
</html>
"""


@dataclass(frozen=True, slots=True)
class TemplateSet:
    """The templates one render uses."""

    html: str = DEFAULT_HTML_TEMPLATE
    css: str = DEFAULT_CSS
    footer: str = "Generated by RAGStrike."
    extra: dict[str, str] = field(default_factory=dict)


class TemplateManager:
    """Loads templates from disk, falling back to the shipped ones.

    A missing template directory is normal, not an error -- the defaults are complete, and a report
    that refuses to render because nobody customized it would be useless out of the box.
    """

    def __init__(self, directory: Path | None = None) -> None:
        self.directory = directory

    def load(self) -> TemplateSet:
        if self.directory is None or not self.directory.is_dir():
            return TemplateSet()

        return TemplateSet(
            html=self._read("report.html", DEFAULT_HTML_TEMPLATE),
            css=self._read("report.css", DEFAULT_CSS),
            footer=self._read("footer.txt", "Generated by RAGStrike.").strip(),
        )

    def _read(self, name: str, fallback: str) -> str:
        if self.directory is None:
            return fallback
        path = self.directory / name
        try:
            return path.read_text(encoding="utf-8")
        except OSError:
            return fallback

    @staticmethod
    def apply(template: str, **values: Any) -> str:
        """Substitute ``$name`` placeholders.

        ``safe_substitute`` rather than ``substitute``: an operator's customized template with a
        stray ``$`` should render with that literal intact, not raise and lose the whole report.
        """
        return Template(template).safe_substitute(**values)


class AssetManager:
    """Supplies assets for embedding.

    Everything is inlined. See the module docstring: a report that depends on sibling files is
    broken the moment it is emailed, which is most of what happens to reports.
    """

    def __init__(self, directory: Path | None = None) -> None:
        self.directory = directory

    def css(self, override: str = "") -> str:
        if override:
            return override
        if self.directory:
            path = self.directory / "report.css"
            try:
                return path.read_text(encoding="utf-8")
            except OSError:
                pass
        return DEFAULT_CSS

    def logo(self, configured: str = "") -> str:
        """A logo placeholder.

        Returns whatever the configuration supplied -- a data URI, a caption, or nothing. The
        engine never fetches a remote image: a report that phones home when opened is a tracking
        pixel, whatever it was meant to be.
        """
        return configured


__all__ = [
    "DEFAULT_CSS",
    "DEFAULT_HTML_TEMPLATE",
    "AssetManager",
    "TemplateManager",
    "TemplateSet",
]
