"""Assembling a :class:`ReportService` from ``configs/reporting/``.

Separated from the engine so constructing one in a test needs no filesystem and no config tree. The
built-in defaults are complete; this is the path that reads an operator's tuning.

**A missing or malformed file degrades, it does not abort**, and what fell back is reported. A tool
that refuses to produce a report because one YAML file has a typo is one that does not get used --
but a tool that silently ignores the branding an operator just configured is worse.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from ragstrike.reporters.builders.report_builder import ReportContext
from ragstrike.reporters.engine.report_engine import REPORT_VERSION, ReportEngine, default_registry
from ragstrike.reporters.html.renderer import HtmlRenderer
from ragstrike.reporters.markdown.renderer import MarkdownRenderer
from ragstrike.reporters.service import ReportService
from ragstrike.reporters.templates.template_manager import AssetManager, TemplateManager

DEFAULT_CONFIG_DIR = Path("configs") / "reporting"


@dataclass(frozen=True, slots=True)
class ReportingConfig:
    """Resolved reporting settings."""

    report_version: str = REPORT_VERSION
    default_formats: tuple[str, ...] = ("html", "json", "markdown")
    output_dir: Path = Path("reports")
    strict_validation: bool = True
    max_detailed_findings: int = 50

    title: str = "RAG Security Assessment"
    organization: str = ""
    logo: str = ""
    theme: str = "auto"
    footer: str = "Generated by RAGStrike."

    template_dir: Path | None = None
    inline_assets: bool = True

    def context(self, **overrides: Any) -> ReportContext:
        """A :class:`ReportContext` pre-filled with branding.

        Saves every caller from copying title, organization, and logo into place, which is how
        those three drift apart between the HTML and the JSON of the same scan.
        """
        values: dict[str, Any] = {
            "title": self.title,
            "organization": self.organization,
            "logo": self.logo,
            "report_version": self.report_version,
        }
        values.update({k: v for k, v in overrides.items() if v is not None})
        return ReportContext(**values)


@dataclass(frozen=True, slots=True)
class ReportingConfigReport:
    """What was loaded and what fell back to defaults."""

    config_dir: Path
    loaded: tuple[str, ...] = ()
    missing: tuple[str, ...] = field(default_factory=tuple)

    @property
    def fully_configured(self) -> bool:
        return not self.missing

    def to_dict(self) -> dict[str, Any]:
        return {
            "config_dir": str(self.config_dir),
            "loaded": list(self.loaded),
            "missing": list(self.missing),
        }


def _read(path: Path, section: str) -> dict[str, Any]:
    """Read one section from a YAML file, tolerating absence and malformation."""
    try:
        raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (yaml.YAMLError, OSError):
        return {}
    if not isinstance(raw, dict):
        return {}
    value = raw.get(section)
    return value if isinstance(value, dict) else {}


def load_config(config_dir: Path | None = None) -> tuple[ReportingConfig, ReportingConfigReport]:
    """Load reporting configuration, with a report of what was actually found."""
    directory = config_dir or DEFAULT_CONFIG_DIR
    loaded: list[str] = []
    missing: list[str] = []

    def track(name: str, filename: str) -> dict[str, Any]:
        path = directory / filename
        (loaded if path.is_file() else missing).append(name)
        return _read(path, name)

    reporting = track("reporting", "reporting.yaml")
    branding = track("branding", "branding.yaml")
    templates = track("templates", "templates.yaml")

    template_dir_raw = str(templates.get("directory", "")).strip()
    template_dir: Path | None = None
    if template_dir_raw:
        candidate = Path(template_dir_raw)
        template_dir = candidate if candidate.is_absolute() else directory / candidate

    defaults = ReportingConfig()
    config = ReportingConfig(
        report_version=str(reporting.get("report_version", defaults.report_version)),
        default_formats=tuple(
            str(f) for f in reporting.get("default_formats", defaults.default_formats)
        ),
        output_dir=Path(str(reporting.get("output_dir", defaults.output_dir))),
        strict_validation=bool(reporting.get("strict_validation", defaults.strict_validation)),
        max_detailed_findings=int(
            reporting.get("max_detailed_findings", defaults.max_detailed_findings)
        ),
        title=str(branding.get("title", defaults.title)),
        organization=str(branding.get("organization", defaults.organization)),
        logo=str(branding.get("logo", defaults.logo)),
        theme=str(branding.get("theme", defaults.theme)),
        footer=str(branding.get("footer", defaults.footer)),
        template_dir=template_dir,
        inline_assets=bool(templates.get("inline_assets", defaults.inline_assets)),
    )

    return config, ReportingConfigReport(
        config_dir=directory, loaded=tuple(loaded), missing=tuple(missing)
    )


def build_service(
    config_dir: Path | None = None,
    *,
    repository: Any = None,
) -> tuple[ReportService, ReportingConfig, ReportingConfigReport]:
    """Build a fully configured :class:`ReportService`.

    Returns the config alongside the service so a caller can reach ``config.context(...)`` without
    loading the files a second time.
    """
    config, report = load_config(config_dir)

    templates = TemplateManager(config.template_dir)
    assets = AssetManager(config.template_dir)

    registry = default_registry()
    # Replace the two renderers that take configuration. The others need none, so rebuilding them
    # would only be ceremony.
    registry.register(HtmlRenderer(templates=templates, assets=assets), replace=True)
    markdown = MarkdownRenderer()
    markdown.max_detailed_findings = config.max_detailed_findings
    registry.register(markdown, replace=True)

    service = ReportService(
        engine=ReportEngine(registry=registry),
        repository=repository,
        output_dir=config.output_dir,
    )
    return service, config, report


__all__ = [
    "DEFAULT_CONFIG_DIR",
    "ReportingConfig",
    "ReportingConfigReport",
    "build_service",
    "load_config",
]
